"""
Turn a captured VO_BrokerTimeProbe.mq5 Journal log into config/settings/brokers.yaml.

The probe observes; vo.time.probe.classify() concludes; this script is the last
step that writes the conclusion down. It does no classification of its own -
every judgment call about DST calendars lives in vo/time/probe.py, where it is
tested against synthetic brokers whose answers are known.

Usage:
    python scripts/seed_broker_profile.py <captured_probe_log> [--out config/settings/brokers.yaml]

The input is the MT5 Experts-tab Journal export, tab-delimited
(timestamp, source, message) per line, exactly as MetaTrader writes it and
exactly as it is committed under tests/fixtures/golden/. Nothing here re-derives
or edits that file - it is read-only evidence.
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "python"))

from vo.time.probe import (
    ClockReading,
    ProbeResult,
    classify,
    parse_probe_output,
)


def extract_json_lines(raw_log: str) -> list[str]:
    """
    Pull just the message payload out of each Journal line.

    MT5's Journal export is tab-delimited: timestamp, source label, message.
    parse_probe_output() only recognises lines starting with '{', so the
    timestamp/source prefix has to come off first. Exact duplicate messages
    (the probe was run twice back to back here) are collapsed so the evidence
    isn't double-counted - dict.fromkeys preserves first-seen order.
    """
    messages = []
    for raw in raw_log.splitlines():
        parts = raw.split("\t")
        candidate = parts[-1].strip() if parts else raw.strip()
        if candidate.startswith("{") or candidate.startswith("VO BROKER TIME PROBE"):
            messages.append(candidate)
    return list(dict.fromkeys(messages))


def render_yaml(server_name: str, symbol: str, result: ProbeResult, clock: ClockReading | None,
                 source_log: str, probe_run_at: str) -> str:
    lines = [
        "# config/settings/brokers.yaml        versioned; changing it bumps the version",
        "#",
        "# Generated by scripts/seed_broker_profile.py from a real VO_BrokerTimeProbe.mq5",
        "# run - not hand-written. dst_calendar/confidence/evidence come verbatim from",
        "# vo.time.probe.classify(); nothing here is a guess.",
        "version: 1",
        "",
        "brokers:",
        f"  {server_name}:",
        f"    symbol_profiled: \"{symbol}\"",
        f"    dst_calendar: {result.calendar}",
        f"    confidence: {result.confidence}",
    ]

    if result.measured_offset_hours is not None:
        lines.append(f"    measured_utc_offset_hours: {result.measured_offset_hours}")
    if result.implied_daily_close_ny:
        lines.append(f"    implied_daily_close_ny: \"{result.implied_daily_close_ny}\"")

    if clock is not None:
        lines.append(f"    readings_agree: {str(clock.readings_agree).lower()}")

    if result.shift_dates:
        lines.append("    shift_dates:")
        for d in result.shift_dates:
            lines.append(f"      - {d.isoformat()}")

    lines.append("    evidence:")
    for e in result.evidence:
        escaped = e.replace('"', '\\"')
        lines.append(f'      - "{escaped}"')

    lines.extend([
        "    provenance:",
        f"      source_log: {source_log}",
        f"      probe_run_at: \"{probe_run_at}\"",
        "      probe_script: mql5/Scripts/VectorOdyssey/VO_BrokerTimeProbe.mq5",
        "      classified_by: vo.time.probe.classify",
    ])

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("log_path", type=Path)
    parser.add_argument("--out", type=Path, default=Path("config/settings/brokers.yaml"))
    args = parser.parse_args()

    raw_log = args.log_path.read_text(encoding="utf-8")
    lines = extract_json_lines(raw_log)

    observations = parse_probe_output(lines)
    result = classify(observations)

    server_name = observations.clock.server_name if observations.clock else "UNKNOWN"

    print(f"server_name       = {server_name}")
    print(f"calendar          = {result.calendar}")
    print(f"confidence        = {result.confidence}")
    print(f"measured_offset_h = {result.measured_offset_hours}")
    print(f"daily_close_ny    = {result.implied_daily_close_ny}")
    print(f"is_conclusive     = {result.is_conclusive}")
    print("evidence:")
    for e in result.evidence:
        print(f"  - {e}")

    symbol = None
    for raw in raw_log.splitlines():
        if '"record_type":"probe_summary"' in raw:
            import json
            payload = raw.split("\t")[-1]
            symbol = json.loads(payload).get("symbol")
            break

    args.out.parent.mkdir(parents=True, exist_ok=True)
    yaml_text = render_yaml(
        server_name=server_name,
        symbol=symbol or "UNKNOWN",
        result=result,
        clock=observations.clock,
        source_log=str(args.log_path.as_posix()),
        probe_run_at=datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )
    args.out.write_text(yaml_text, encoding="utf-8")
    print(f"\nWrote {args.out}")

    return 0 if result.is_conclusive else 1


if __name__ == "__main__":
    raise SystemExit(main())
